# Generated by Django 5.1.5 on 2025-10-14 17:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='код')),
                ('wa_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None, unique=True, verbose_name='номер WhatsApp')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientBatchImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_text', models.TextField(verbose_name='Список клиентов')),
            ],
            options={
                'verbose_name': 'Импорт клиентских партий',
                'verbose_name_plural': 'Импорт клиентских партий',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=1000, null=True, verbose_name='штрих-код')),
                ('date', models.DateField(verbose_name='дата')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена')),
                ('sent_to_client', models.BooleanField(default=False, verbose_name='отправлено клиенту')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='cargo.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
