# Generated by Django 5.1.5 on 2026-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='код'),
        ),
    ]
